server:
  port: 8888
  servlet:
    context-path: /shop/api/v1/

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoanghuutuyen060204@gmail.com
    password: hass qchm rasg rzxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/test3?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:12345678}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE:Asia/Ho_Chi_Minh}
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${SIGNED_KEY:4FUNMjFiPr1J29IIqbjc7QbPpX2RPfQSVAH8b5dQHVK5XxyTdjC6Ax9DG8YodTb5}

amazon:
  accessKey: ${ACCESS_KEY:AKIAVRUVSN7O6R7B34E2}
  secretKey: ${SECRET_KEY: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}
  region: ${REGION:ap-southeast-1}
  bucket-name: ${BUCKET_NAME:tuyen-third-bucket}